### ISSUE TITLE
[INFO] - Explanation of numbers / signs?

### ISSUE THREAD

**Issue by CJamesKeller** [retorillo/istanbul.vim#16]
The blue-on-white numbers used as signs beside covered lines of code are not explained. Does a line with "01" next to it differ in any significant way from a line with "04" or "06" next to it?

If so, could this be documented somewhere?

If not, what do these numbers mean? Can they be suppressed (so that only the red signs for uncovered lines are shown)?

Thank you for this plugin!

**Comment by retorillo** [comment]
Thank you for using my plugin!

These number means "Execution count", so displayed at only blue (executed) line, and shows always 99 if execution count is 100 or over.

I'm sorry that these things are not documented, want to update README later!

**Comment by CJamesKeller** [comment]
Sounds good, thank you!
